class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start4'
        self.MirrorCommand = 'dl4'
        self.UnzipMirrorCommand = 'unzip4'
        self.TarMirrorCommand = 'tar4'
        self.ZipMirrorCommand = 'zip4'
        self.CancelMirror = 'batal4'
        self.CancelAllCommand = 'batalin4'
        self.ListCommand = 'cari4'
        self.StatusCommand = 'status4'
        self.AuthorizedUsersCommand = 'users4'
        self.AuthorizeCommand = 'auth4'
        self.UnAuthorizeCommand = 'unauth4'
        self.AddSudoCommand = 'addsudo4'
        self.RmSudoCommand = 'rmsudo4'
        self.PingCommand = 'ping4'
        self.RestartCommand = 'restart4'
        self.StatsCommand = 'stat4'
        self.HelpCommand = 'bantuan4'
        self.LogCommand = 'log4'
        self.SpeedCommand = 'speedtest4'
        self.CloneCommand = 'salin4'
        self.CountCommand = 'hitung4'
        self.WatchCommand = 'watch4'
        self.TarWatchCommand = 'tarwatch4'
        self.DeleteCommand = 'del4'
        self.ConfigMenuCommand = 'config4'
        self.ShellCommand = 'shell4'
        self.UpdateCommand = 'update4'
        self.ExecHelpCommand = 'exechelp4'
        self.TsHelpCommand = 'tshelp4'

BotCommands = _BotCommands()
